<?php
// Path: resources/lang/en/auth.php

return [
    'module_name' => 'Authentication',
    
    // Login & Sessions
    'login' => 'Log In',
    'logout' => 'Log Out',
    'email' => 'Email Address',
    'password' => 'Password',
    'remember_me' => 'Remember Me',
    'forgot_password' => 'Forgot Password?',
    'sign_in_to_dashboard' => 'Sign In to Dashboard',
    
    // Reset Password
    'reset_password' => 'Reset Password',
    'send_reset_link' => 'Send Reset Link',
    'back_to_login' => 'Back to Login',
    'new_password' => 'New Password',
    'confirm_password' => 'Confirm Password',
    
    // Two-Factor Auth (2FA)
    'two_factor_auth' => 'Two-Factor Authentication',
    'verify_2fa' => 'Verify 2FA Code',
    'enter_code' => 'Enter the authentication code generated by your app.',
    'setup_2fa' => 'Setup 2FA',
    'disable_2fa' => 'Disable 2FA',
    
    // Messages
    'failed' => 'These credentials do not match our records.',
    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
    'session_expired' => 'Your session has expired. Please log in again.',
    'logged_out' => 'You have been successfully logged out.',
    'password_reset_sent' => 'We have emailed your password reset link!',
];