<?php
// Path: resources/views/enterprise/supply-chain/dashboard.php
$pageTitle = 'Supply Chain Control Tower';
ob_start();
?>

<div class="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between">
    <div>
        <nav class="flex text-sm text-gray-500 mb-1" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-2">
                <li class="inline-flex items-center">
                    <a href="/dashboard" class="hover:text-nour-primary transition-colors"><i class="fas fa-home mr-1"></i> Home</a>
                </li>
                <li>
                    <div class="flex items-center">
                        <i class="fas fa-chevron-right text-xs mx-2"></i>
                        <span>Enterprise</span>
                    </div>
                </li>
                <li>
                    <div class="flex items-center">
                        <i class="fas fa-chevron-right text-xs mx-2"></i>
                        <span class="text-gray-800 font-medium">Supply Chain</span>
                    </div>
                </li>
            </ol>
        </nav>
        <h1 class="text-2xl font-bold text-gray-800">Control Tower</h1>
        <p class="text-sm text-gray-500 mt-1">Monitor demand forecasts, automated replenishment, and supply health.</p>
    </div>
    
    <div class="mt-4 sm:mt-0 flex gap-3">
        <button class="bg-white border border-gray-300 text-gray-700 px-4 py-2 rounded-lg shadow-sm text-sm font-medium hover:bg-gray-50 transition-colors flex items-center" onclick="showToast('Executing MRP Engine...', 'info')">
            <i class="fas fa-cogs mr-2 text-nour-primary"></i> Run MRP
        </button>
        <button class="btn-primary flex items-center shadow-md shadow-nour-primary/30" onclick="showToast('Demand forecasting algorithm started.', 'success')">
            <i class="fas fa-chart-line mr-2"></i> Generate Forecast
        </button>
    </div>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-6">
    <!-- Forecast Accuracy -->
    <div class="card p-5 border-l-4 border-l-nour-primary relative overflow-hidden group">
        <div class="absolute right-0 top-0 mt-4 mr-4 text-nour-primary/10 group-hover:scale-110 transition-transform duration-300">
            <i class="fas fa-bullseye text-5xl"></i>
        </div>
        <div class="relative z-10">
            <p class="text-sm font-medium text-gray-500 uppercase tracking-wider mb-1">Forecast Accuracy</p>
            <h3 class="text-3xl font-bold text-gray-900">92.4%</h3>
            <div class="mt-4 text-sm text-gray-500 flex items-center">
                <span class="text-green-500 font-medium mr-2"><i class="fas fa-arrow-up"></i> 1.2%</span> vs last month
            </div>
        </div>
    </div>
    
    <!-- Auto-Reorders Pending -->
    <div class="card p-5 border-l-4 border-l-blue-500 relative overflow-hidden group">
        <div class="absolute right-0 top-0 mt-4 mr-4 text-blue-500/10 group-hover:scale-110 transition-transform duration-300">
            <i class="fas fa-robot text-5xl"></i>
        </div>
        <div class="relative z-10">
            <p class="text-sm font-medium text-gray-500 uppercase tracking-wider mb-1">Automated Reorders</p>
            <h3 class="text-3xl font-bold text-blue-600">24</h3>
            <div class="mt-4 text-sm text-gray-500">
                Pending PRs generated by system
            </div>
        </div>
    </div>

    <!-- Incoming Supply Value -->
    <div class="card p-5 border-l-4 border-l-green-500 relative overflow-hidden group">
        <div class="absolute right-0 top-0 mt-4 mr-4 text-green-500/10 group-hover:scale-110 transition-transform duration-300">
            <i class="fas fa-truck-loading text-5xl"></i>
        </div>
        <div class="relative z-10">
            <p class="text-sm font-medium text-gray-500 uppercase tracking-wider mb-1">In-Transit Value</p>
            <h3 class="text-3xl font-bold text-gray-900">$485.2K</h3>
            <div class="mt-4 text-sm text-gray-500 flex items-center">
                Across <span class="font-medium text-gray-800 mx-1">12</span> active Purchase Orders
            </div>
        </div>
    </div>

    <!-- Critical Shortages -->
    <div class="card p-5 border-l-4 border-l-red-500 relative overflow-hidden group">
        <div class="absolute right-0 top-0 mt-4 mr-4 text-red-500/10 group-hover:scale-110 transition-transform duration-300">
            <i class="fas fa-exclamation-triangle text-5xl"></i>
        </div>
        <div class="relative z-10">
            <p class="text-sm font-medium text-gray-500 uppercase tracking-wider mb-1">Critical Shortages</p>
            <h3 class="text-3xl font-bold text-red-600">8</h3>
            <div class="mt-4 text-sm text-red-500 font-medium">
                Items below safety stock level!
            </div>
        </div>
    </div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
    <!-- Demand vs Supply Trend Chart -->
    <div class="card col-span-1 lg:col-span-2 p-5 flex flex-col">
        <div class="flex justify-between items-center mb-4">
            <div>
                <h3 class="text-lg font-bold text-gray-800">Demand vs Supply Projection</h3>
                <p class="text-xs text-gray-500">6-Month rolling forecast</p>
            </div>
            <select class="text-sm border-gray-300 rounded-md focus:ring-nour-primary text-gray-600 bg-gray-50 py-1">
                <option>All Warehouses</option>
                <option>HQ - Riyadh WH</option>
                <option>Jeddah WH</option>
            </select>
        </div>
        
        <!-- CSS-based visual representation of chart for UI completeness -->
        <div class="flex-1 min-h-[250px] w-full bg-gray-50 border border-dashed border-gray-200 rounded-lg flex items-end justify-between p-4 relative">
            <!-- Y-Axis labels -->
            <div class="absolute left-2 top-4 bottom-8 flex flex-col justify-between text-[10px] text-gray-400">
                <span>10k</span><span>8k</span><span>6k</span><span>4k</span><span>2k</span><span>0</span>
            </div>
            
            <!-- Grid Lines -->
            <div class="absolute left-8 right-2 top-6 h-px bg-gray-200"></div>
            <div class="absolute left-8 right-2 top-1/4 h-px bg-gray-200"></div>
            <div class="absolute left-8 right-2 top-2/4 h-px bg-gray-200"></div>
            <div class="absolute left-8 right-2 top-3/4 h-px bg-gray-200"></div>
            <div class="absolute left-8 right-2 bottom-8 h-px bg-gray-300"></div>

            <!-- Chart Bars -->
            <div class="w-full flex justify-around items-end h-[calc(100%-2rem)] pl-8 z-10">
                <!-- Month 1 -->
                <div class="w-1/6 flex justify-center gap-1 group relative">
                    <div class="w-3 bg-nour-primary rounded-t-sm h-[40%] group-hover:opacity-80 transition-opacity"></div>
                    <div class="w-3 bg-nour-light rounded-t-sm h-[45%] group-hover:opacity-80 transition-opacity"></div>
                    <span class="absolute -bottom-6 text-[10px] text-gray-500 font-medium">May</span>
                </div>
                <!-- Month 2 -->
                <div class="w-1/6 flex justify-center gap-1 group relative">
                    <div class="w-3 bg-nour-primary rounded-t-sm h-[55%] group-hover:opacity-80 transition-opacity"></div>
                    <div class="w-3 bg-nour-light rounded-t-sm h-[50%] group-hover:opacity-80 transition-opacity"></div>
                    <span class="absolute -bottom-6 text-[10px] text-gray-500 font-medium">Jun</span>
                </div>
                <!-- Month 3 -->
                <div class="w-1/6 flex justify-center gap-1 group relative">
                    <div class="w-3 bg-nour-primary rounded-t-sm h-[48%] group-hover:opacity-80 transition-opacity"></div>
                    <div class="w-3 bg-nour-light rounded-t-sm h-[60%] group-hover:opacity-80 transition-opacity"></div>
                    <span class="absolute -bottom-6 text-[10px] text-gray-500 font-medium">Jul</span>
                </div>
                <!-- Month 4 (Current) -->
                <div class="w-1/6 flex justify-center gap-1 group relative">
                    <div class="w-3 bg-nour-primary rounded-t-sm h-[70%] group-hover:opacity-80 transition-opacity"></div>
                    <div class="w-3 bg-nour-light rounded-t-sm h-[65%] group-hover:opacity-80 transition-opacity"></div>
                    <span class="absolute -bottom-6 text-[10px] text-gray-900 font-bold bg-gray-200 px-2 py-0.5 rounded">Aug</span>
                </div>
                <!-- Month 5 (Forecast) -->
                <div class="w-1/6 flex justify-center gap-1 group relative opacity-60">
                    <div class="w-3 bg-nour-primary rounded-t-sm h-[85%] border-t-2 border-dashed border-white"></div>
                    <div class="w-3 bg-nour-light rounded-t-sm h-[80%] border-t-2 border-dashed border-white"></div>
                    <span class="absolute -bottom-6 text-[10px] text-gray-400 font-medium">Sep</span>
                </div>
                <!-- Month 6 (Forecast) -->
                <div class="w-1/6 flex justify-center gap-1 group relative opacity-60">
                    <div class="w-3 bg-nour-primary rounded-t-sm h-[90%] border-t-2 border-dashed border-white"></div>
                    <div class="w-3 bg-nour-light rounded-t-sm h-[85%] border-t-2 border-dashed border-white"></div>
                    <span class="absolute -bottom-6 text-[10px] text-gray-400 font-medium">Oct</span>
                </div>
            </div>
        </div>
        
        <div class="flex justify-center gap-6 mt-4">
            <div class="flex items-center text-xs text-gray-600"><span class="w-3 h-3 rounded-full bg-nour-primary mr-2"></span> Projected Demand</div>
            <div class="flex items-center text-xs text-gray-600"><span class="w-3 h-3 rounded-full bg-nour-light mr-2"></span> Planned Supply</div>
        </div>
    </div>

    <!-- Inventory Health -->
    <div class="card col-span-1 p-5">
        <h3 class="text-lg font-bold text-gray-800 mb-4">Inventory Health</h3>
        
        <div class="space-y-5">
            <!-- Metric 1 -->
            <div>
                <div class="flex justify-between items-center mb-1">
                    <span class="text-sm font-medium text-gray-700">Healthy Stock</span>
                    <span class="text-sm font-bold text-gray-900">65%</span>
                </div>
                <div class="w-full bg-gray-100 rounded-full h-2">
                    <div class="bg-green-500 h-2 rounded-full" style="width: 65%"></div>
                </div>
            </div>
            
            <!-- Metric 2 -->
            <div>
                <div class="flex justify-between items-center mb-1">
                    <span class="text-sm font-medium text-gray-700">Excess / Overstock</span>
                    <span class="text-sm font-bold text-gray-900">22%</span>
                </div>
                <div class="w-full bg-gray-100 rounded-full h-2">
                    <div class="bg-yellow-400 h-2 rounded-full" style="width: 22%"></div>
                </div>
            </div>
            
            <!-- Metric 3 -->
            <div>
                <div class="flex justify-between items-center mb-1">
                    <span class="text-sm font-medium text-gray-700">Low Stock / Shortage</span>
                    <span class="text-sm font-bold text-gray-900">13%</span>
                </div>
                <div class="w-full bg-gray-100 rounded-full h-2">
                    <div class="bg-red-500 h-2 rounded-full" style="width: 13%"></div>
                </div>
            </div>
        </div>
        
        <div class="mt-8 pt-5 border-t border-gray-100">
            <h4 class="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">Landed Cost Adjustments</h4>
            <div class="bg-gray-50 rounded-lg p-3 flex justify-between items-center border border-gray-200">
                <div class="flex items-center">
                    <div class="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center mr-3">
                        <i class="fas fa-file-invoice-dollar text-xs"></i>
                    </div>
                    <div>
                        <p class="text-sm font-medium text-gray-800">Pending Allocations</p>
                        <p class="text-xs text-gray-500">Awaiting clearance</p>
                    </div>
                </div>
                <span class="px-2.5 py-1 bg-blue-100 text-blue-800 text-xs font-bold rounded-full">3 Docs</span>
            </div>
        </div>
    </div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <!-- Critical Shortages Table -->
    <div class="card p-0 overflow-hidden flex flex-col">
        <div class="px-5 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
            <h3 class="text-base font-bold text-gray-800"><i class="fas fa-exclamation-circle text-red-500 mr-2"></i> Critical Items (Below Safety)</h3>
            <a href="/supply-chain/safety-stock" class="text-sm font-medium text-nour-primary hover:underline">View Policy</a>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full text-left border-collapse">
                <thead>
                    <tr class="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider border-b border-gray-100">
                        <th class="p-3 font-semibold">SKU / Product</th>
                        <th class="p-3 font-semibold text-right">Available</th>
                        <th class="p-3 font-semibold text-right">Min. Required</th>
                        <th class="p-3 font-semibold text-center">Action</th>
                    </tr>
                </thead>
                <tbody class="text-sm divide-y divide-gray-100">
                    <tr class="hover:bg-gray-50 transition-colors group">
                        <td class="p-3">
                            <span class="block font-semibold text-gray-800">CBL-COP-001</span>
                            <span class="block text-xs text-gray-500 truncate w-40">Copper Cable 5mm</span>
                        </td>
                        <td class="p-3 text-right font-bold text-red-600">120 M</td>
                        <td class="p-3 text-right text-gray-600">500 M</td>
                        <td class="p-3 text-center">
                            <button class="bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 px-2 py-1 rounded text-xs font-medium transition-colors shadow-sm">
                                Reorder
                            </button>
                        </td>
                    </tr>
                    <tr class="hover:bg-gray-50 transition-colors group">
                        <td class="p-3">
                            <span class="block font-semibold text-gray-800">CHIP-INT-X9</span>
                            <span class="block text-xs text-gray-500 truncate w-40">Processor Unit X9</span>
                        </td>
                        <td class="p-3 text-right font-bold text-red-600">5 Pcs</td>
                        <td class="p-3 text-right text-gray-600">20 Pcs</td>
                        <td class="p-3 text-center">
                            <span class="text-[10px] uppercase font-bold text-blue-600 bg-blue-50 px-2 py-1 rounded">PO Sent</span>
                        </td>
                    </tr>
                    <tr class="hover:bg-gray-50 transition-colors group">
                        <td class="p-3">
                            <span class="block font-semibold text-gray-800">PKG-BOX-L</span>
                            <span class="block text-xs text-gray-500 truncate w-40">Large Packaging Box</span>
                        </td>
                        <td class="p-3 text-right font-bold text-red-600">0 Pcs</td>
                        <td class="p-3 text-right text-gray-600">1000 Pcs</td>
                        <td class="p-3 text-center">
                            <button class="bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 px-2 py-1 rounded text-xs font-medium transition-colors shadow-sm">
                                Reorder
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <!-- Upcoming Deliveries Table -->
    <div class="card p-0 overflow-hidden flex flex-col">
        <div class="px-5 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
            <h3 class="text-base font-bold text-gray-800"><i class="fas fa-ship text-nour-primary mr-2"></i> Expected Deliveries</h3>
            <a href="/purchasing/purchase-orders" class="text-sm font-medium text-nour-primary hover:underline">Track POs</a>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full text-left border-collapse">
                <thead>
                    <tr class="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider border-b border-gray-100">
                        <th class="p-3 font-semibold">PO Number</th>
                        <th class="p-3 font-semibold">Supplier</th>
                        <th class="p-3 font-semibold">Exp. Date</th>
                        <th class="p-3 font-semibold text-right">Status</th>
                    </tr>
                </thead>
                <tbody class="text-sm divide-y divide-gray-100">
                    <tr class="hover:bg-gray-50 transition-colors group">
                        <td class="p-3 font-medium text-nour-primary">PO-2608-042</td>
                        <td class="p-3 text-gray-800">Global Tech Suppliers</td>
                        <td class="p-3 text-gray-600">Tomorrow</td>
                        <td class="p-3 text-right">
                            <span class="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-blue-100 text-blue-800">
                                In Transit
                            </span>
                        </td>
                    </tr>
                    <tr class="hover:bg-gray-50 transition-colors group">
                        <td class="p-3 font-medium text-nour-primary">PO-2608-038</td>
                        <td class="p-3 text-gray-800">Alpha Manufacturing</td>
                        <td class="p-3 text-gray-600">Aug 20, 2026</td>
                        <td class="p-3 text-right">
                            <span class="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-yellow-100 text-yellow-800">
                                Packing
                            </span>
                        </td>
                    </tr>
                    <tr class="hover:bg-gray-50 transition-colors group">
                        <td class="p-3 font-medium text-nour-primary">PO-2608-045</td>
                        <td class="p-3 text-gray-800">Logistics Corp HQ</td>
                        <td class="p-3 text-red-500 font-medium">Overdue (2 Days)</td>
                        <td class="p-3 text-right">
                            <span class="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-red-100 text-red-800">
                                Delayed
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php
$content = ob_get_clean();
require_once __DIR__ . '/../../layouts/app.php';
?>