<?php
// Path: app/Core/Routing/Router.php

declare(strict_types=1);

namespace App\Core\Routing;

use Exception;
use App\Core\Http\Request;

/**
 * Enterprise Router
 * Registers routes and dispatches incoming requests to the appropriate handler.
 */
class Router
{
    /**
     * The registered routes.
     *
     * @var array<Route>
     */
    protected array $routes = [];

    /**
     * Register a new route.
     *
     * @param array|string $methods
     * @param string $uri
     * @param mixed $action
     * @return Route
     */
    public function addRoute(array|string $methods, string $uri, mixed $action): Route
    {
        $route = new Route($methods, $uri, $action);
        $this->routes[] = $route;
        return $route;
    }

    /**
     * Register a GET route.
     *
     * @param string $uri
     * @param mixed $action
     * @return Route
     */
    public function get(string $uri, mixed $action): Route
    {
        return $this->addRoute(['GET', 'HEAD'], $uri, $action);
    }

    /**
     * Register a POST route.
     *
     * @param string $uri
     * @param mixed $action
     * @return Route
     */
    public function post(string $uri, mixed $action): Route
    {
        return $this->addRoute('POST', $uri, $action);
    }

    /**
     * Register a PUT route.
     *
     * @param string $uri
     * @param mixed $action
     * @return Route
     */
    public function put(string $uri, mixed $action): Route
    {
        return $this->addRoute('PUT', $uri, $action);
    }

    /**
     * Register a DELETE route.
     *
     * @param string $uri
     * @param mixed $action
     * @return Route
     */
    public function delete(string $uri, mixed $action): Route
    {
        return $this->addRoute('DELETE', $uri, $action);
    }

    /**
     * Dispatch the request to the matching route.
     *
     * @param Request $request
     * @return mixed The response content.
     * @throws Exception If no route matches or method is not allowed.
     */
    public function dispatch(Request $request): mixed
    {
        $method = $request->method();
        $uri = $request->uri();

        // 1. Find matching route based on URI
        $matchingRoutes = array_filter($this->routes, fn (Route $route) => $route->matches($uri));

        if (empty($matchingRoutes)) {
            throw new Exception("404 Not Found: No route matches the requested URI [{$uri}].", 404);
        }

        // 2. Filter by HTTP Method
        $route = null;
        foreach ($matchingRoutes as $matchedRoute) {
            if (in_array($method, $matchedRoute->getMethods())) {
                $route = $matchedRoute;
                break;
            }
        }

        if (!$route) {
            throw new Exception("405 Method Not Allowed: Method [{$method}] not allowed for URI [{$uri}].", 405);
        }

        // 3. (Future) Handle Middleware here before executing action

        // 4. Execute the Action
        return $this->executeAction($route, $request);
    }

    /**
     * Execute the route action.
     *
     * @param Route $route
     * @param Request $request
     * @return mixed
     * @throws Exception
     */
   protected function executeAction(
    Route $route,
    Request $request
): mixed {
    $action = $route->getAction();
    $parameters = $route->getParameters();

    /**
     * Capture any direct output generated by views.
     */
    ob_start();

    try {
        /*
        |--------------------------------------------------------------------------
        | Callable / Closure
        |--------------------------------------------------------------------------
        */
        if (is_callable($action)) {
            $result = call_user_func_array(
                $action,
                array_merge(
                    [$request],
                    $parameters
                )
            );
        }

        /*
        |--------------------------------------------------------------------------
        | Controller Action
        |--------------------------------------------------------------------------
        */
        elseif (
            is_array($action)
            && count($action) === 2
        ) {
            [$class, $method] = $action;

            if (!class_exists($class)) {
                throw new Exception(
                    "Target class [{$class}] does not exist."
                );
            }

            $controller = new $class();

            if (!method_exists($controller, $method)) {
                throw new Exception(
                    "Method [{$method}] does not exist on class [{$class}]."
                );
            }

            $result = call_user_func_array(
                [$controller, $method],
                array_merge(
                    [$request],
                    $parameters
                )
            );
        }

        else {
            throw new Exception(
                'Invalid route action defined.'
            );
        }

        /*
        |--------------------------------------------------------------------------
        | Collect View Output
        |--------------------------------------------------------------------------
        */
        $output = ob_get_clean();

        /*
        |--------------------------------------------------------------------------
        | Proper Response Object
        |--------------------------------------------------------------------------
        */
        if ($result instanceof \App\Core\Http\Response) {
            return $result;
        }

        /*
        |--------------------------------------------------------------------------
        | String Response
        |--------------------------------------------------------------------------
        */
        if (is_string($result)) {
            return new \App\Core\Http\Response(
                $output . $result,
                200,
                [
                    'Content-Type' => 'text/html; charset=UTF-8',
                ]
            );
        }

        /*
        |--------------------------------------------------------------------------
        | Null Result + Direct View Output
        |--------------------------------------------------------------------------
        */
        if ($result === null && $output !== '') {
            return new \App\Core\Http\Response(
                $output,
                200,
                [
                    'Content-Type' => 'text/html; charset=UTF-8',
                ]
            );
        }

        /*
        |--------------------------------------------------------------------------
        | Null Result + No Output
        |--------------------------------------------------------------------------
        */
        if ($result === null) {
            throw new Exception(
                'Route action returned null and produced no output.'
            );
        }

        /*
        |--------------------------------------------------------------------------
        | Any Other Return Type
        |--------------------------------------------------------------------------
        */
        return new \App\Core\Http\Response(
            (string) $result,
            200
        );

    } catch (\Throwable $e) {

        if (ob_get_level() > 0) {
            ob_end_clean();
        }

        throw $e;
    }
}
}